### ISSUE TITLE
can you give me a help: do you has has version list or maven repository？

### ISSUE THREAD

**Issue by maxpup** [cronn/validation-file-assertions#5]
Hello, this is a good idea, and it may help our unit test assert, and I really want to try it. 
but I did'nt find maven dependency, can you give me a help?

**Comment by chrisingenhaag** [comment]
Hi @maxpup,
pls take a look into the projects readme. There is a description of how to use it with maven or gradle. Additionally you can see [here](https://search.maven.org/artifact/de.cronn/validation-file-assertions) for example that it is published to maven central.

cheers, Christian
